import localFont from "next/font/local";
import "./globals.css";

const evolventaFont = localFont({
  src: "../../public/fonts/Evolventa-Regular.woff",
  variable: "--font-evolventa",
  weight: "400",
  style: 'normal',

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${evolventaFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
