import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Evolventa-Regular.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});1
const geistMono = localFont({
  src: "./fonts/Evolventa-Oblique.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
